/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiQuizAttemptsRouteImport } from './routes/api/quiz-attempts'
import { Route as ApiStudentsRouteImport } from './routes/api/students'
import { Route as MateriIndexRouteImport } from './routes/materi/index'
import { Route as QuizIndexRouteImport } from './routes/quiz/index'
import { Route as MateriIdIndexRouteImport } from './routes/materi/$id/index'
import { Route as MateriIdArRouteImport } from './routes/materi/$id/ar'
import { Route as MateriIdDiskusiRouteImport } from './routes/materi/$id/diskusi'
import { Route as MateriIdViewerRouteImport } from './routes/materi/$id/viewer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuizAttemptsRoute = ApiQuizAttemptsRouteImport.update({
  id: '/api/quiz-attempts',
  path: '/api/quiz-attempts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsRoute = ApiStudentsRouteImport.update({
  id: '/api/students',
  path: '/api/students',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriIndexRoute = MateriIndexRouteImport.update({
  id: '/materi/',
  path: '/materi/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriIdIndexRoute = MateriIdIndexRouteImport.update({
  id: '/materi/$id/',
  path: '/materi/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriIdArRoute = MateriIdArRouteImport.update({
  id: '/materi/$id/ar',
  path: '/materi/$id/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriIdDiskusiRoute = MateriIdDiskusiRouteImport.update({
  id: '/materi/$id/diskusi',
  path: '/materi/$id/diskusi',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriIdViewerRoute = MateriIdViewerRouteImport.update({
  id: '/materi/$id/viewer',
  path: '/materi/$id/viewer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/quiz-attempts': typeof ApiQuizAttemptsRoute
  '/api/students': typeof ApiStudentsRoute
  '/materi/': typeof MateriIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/materi/$id/ar': typeof MateriIdArRoute
  '/materi/$id/diskusi': typeof MateriIdDiskusiRoute
  '/materi/$id/viewer': typeof MateriIdViewerRoute
  '/materi/$id/': typeof MateriIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/quiz-attempts': typeof ApiQuizAttemptsRoute
  '/api/students': typeof ApiStudentsRoute
  '/materi': typeof MateriIndexRoute
  '/quiz': typeof QuizIndexRoute
  '/materi/$id/ar': typeof MateriIdArRoute
  '/materi/$id/diskusi': typeof MateriIdDiskusiRoute
  '/materi/$id/viewer': typeof MateriIdViewerRoute
  '/materi/$id': typeof MateriIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/quiz-attempts': typeof ApiQuizAttemptsRoute
  '/api/students': typeof ApiStudentsRoute
  '/materi/': typeof MateriIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/materi/$id/ar': typeof MateriIdArRoute
  '/materi/$id/diskusi': typeof MateriIdDiskusiRoute
  '/materi/$id/viewer': typeof MateriIdViewerRoute
  '/materi/$id/': typeof MateriIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/health'
    | '/api/quiz-attempts'
    | '/api/students'
    | '/materi/'
    | '/quiz/'
    | '/materi/$id/ar'
    | '/materi/$id/diskusi'
    | '/materi/$id/viewer'
    | '/materi/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/health'
    | '/api/quiz-attempts'
    | '/api/students'
    | '/materi'
    | '/quiz'
    | '/materi/$id/ar'
    | '/materi/$id/diskusi'
    | '/materi/$id/viewer'
    | '/materi/$id'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/health'
    | '/api/quiz-attempts'
    | '/api/students'
    | '/materi/'
    | '/quiz/'
    | '/materi/$id/ar'
    | '/materi/$id/diskusi'
    | '/materi/$id/viewer'
    | '/materi/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiQuizAttemptsRoute: typeof ApiQuizAttemptsRoute
  ApiStudentsRoute: typeof ApiStudentsRoute
  MateriIndexRoute: typeof MateriIndexRoute
  QuizIndexRoute: typeof QuizIndexRoute
  MateriIdArRoute: typeof MateriIdArRoute
  MateriIdDiskusiRoute: typeof MateriIdDiskusiRoute
  MateriIdViewerRoute: typeof MateriIdViewerRoute
  MateriIdIndexRoute: typeof MateriIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quiz-attempts': {
      id: '/api/quiz-attempts'
      path: '/api/quiz-attempts'
      fullPath: '/api/quiz-attempts'
      preLoaderRoute: typeof ApiQuizAttemptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students': {
      id: '/api/students'
      path: '/api/students'
      fullPath: '/api/students'
      preLoaderRoute: typeof ApiStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materi/': {
      id: '/materi/'
      path: '/materi'
      fullPath: '/materi/'
      preLoaderRoute: typeof MateriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materi/$id/': {
      id: '/materi/$id/'
      path: '/materi/$id'
      fullPath: '/materi/$id/'
      preLoaderRoute: typeof MateriIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materi/$id/ar': {
      id: '/materi/$id/ar'
      path: '/materi/$id/ar'
      fullPath: '/materi/$id/ar'
      preLoaderRoute: typeof MateriIdArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materi/$id/diskusi': {
      id: '/materi/$id/diskusi'
      path: '/materi/$id/diskusi'
      fullPath: '/materi/$id/diskusi'
      preLoaderRoute: typeof MateriIdDiskusiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materi/$id/viewer': {
      id: '/materi/$id/viewer'
      path: '/materi/$id/viewer'
      fullPath: '/materi/$id/viewer'
      preLoaderRoute: typeof MateriIdViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiQuizAttemptsRoute: ApiQuizAttemptsRoute,
  ApiStudentsRoute: ApiStudentsRoute,
  MateriIndexRoute: MateriIndexRoute,
  QuizIndexRoute: QuizIndexRoute,
  MateriIdArRoute: MateriIdArRoute,
  MateriIdDiskusiRoute: MateriIdDiskusiRoute,
  MateriIdViewerRoute: MateriIdViewerRoute,
  MateriIdIndexRoute: MateriIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
