/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MateriIndexRouteImport } from './routes/materi/index'
import { Route as QuizIdRouteImport } from './routes/quiz/$id'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as MateriIdIndexRouteImport } from './routes/materi/$id/index'
import { Route as MateriIdViewerRouteImport } from './routes/materi/$id/viewer'
import { Route as MateriIdArRouteImport } from './routes/materi/$id/ar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriIndexRoute = MateriIndexRouteImport.update({
  id: '/materi/',
  path: '/materi/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIdRoute = QuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriIdIndexRoute = MateriIdIndexRouteImport.update({
  id: '/materi/$id/',
  path: '/materi/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriIdViewerRoute = MateriIdViewerRouteImport.update({
  id: '/materi/$id/viewer',
  path: '/materi/$id/viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriIdArRoute = MateriIdArRouteImport.update({
  id: '/materi/$id/ar',
  path: '/materi/$id/ar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/quiz/$id': typeof QuizIdRoute
  '/materi/': typeof MateriIndexRoute
  '/materi/$id/ar': typeof MateriIdArRoute
  '/materi/$id/viewer': typeof MateriIdViewerRoute
  '/materi/$id/': typeof MateriIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/quiz/$id': typeof QuizIdRoute
  '/materi': typeof MateriIndexRoute
  '/materi/$id/ar': typeof MateriIdArRoute
  '/materi/$id/viewer': typeof MateriIdViewerRoute
  '/materi/$id': typeof MateriIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/quiz/$id': typeof QuizIdRoute
  '/materi/': typeof MateriIndexRoute
  '/materi/$id/ar': typeof MateriIdArRoute
  '/materi/$id/viewer': typeof MateriIdViewerRoute
  '/materi/$id/': typeof MateriIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/health'
    | '/quiz/$id'
    | '/materi/'
    | '/materi/$id/ar'
    | '/materi/$id/viewer'
    | '/materi/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/health'
    | '/quiz/$id'
    | '/materi'
    | '/materi/$id/ar'
    | '/materi/$id/viewer'
    | '/materi/$id'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/health'
    | '/quiz/$id'
    | '/materi/'
    | '/materi/$id/ar'
    | '/materi/$id/viewer'
    | '/materi/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  QuizIdRoute: typeof QuizIdRoute
  MateriIndexRoute: typeof MateriIndexRoute
  MateriIdArRoute: typeof MateriIdArRoute
  MateriIdViewerRoute: typeof MateriIdViewerRoute
  MateriIdIndexRoute: typeof MateriIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materi/': {
      id: '/materi/'
      path: '/materi'
      fullPath: '/materi/'
      preLoaderRoute: typeof MateriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$id': {
      id: '/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof QuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materi/$id/': {
      id: '/materi/$id/'
      path: '/materi/$id'
      fullPath: '/materi/$id/'
      preLoaderRoute: typeof MateriIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materi/$id/viewer': {
      id: '/materi/$id/viewer'
      path: '/materi/$id/viewer'
      fullPath: '/materi/$id/viewer'
      preLoaderRoute: typeof MateriIdViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materi/$id/ar': {
      id: '/materi/$id/ar'
      path: '/materi/$id/ar'
      fullPath: '/materi/$id/ar'
      preLoaderRoute: typeof MateriIdArRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHealthRoute: ApiHealthRoute,
  QuizIdRoute: QuizIdRoute,
  MateriIndexRoute: MateriIndexRoute,
  MateriIdArRoute: MateriIdArRoute,
  MateriIdViewerRoute: MateriIdViewerRoute,
  MateriIdIndexRoute: MateriIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
